plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.pedrodequeiroz.duplaexclusao'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.pedrodequeiroz.duplaexclusao.limpa'
        minSdk 23
        targetSdk 28
        versionCode 18
        versionName '1.8-clean'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
